// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_alpha_diversity_metrics
Rcpp::NumericMatrix compute_alpha_diversity_metrics(Rcpp::NumericMatrix abundances, bool compute_richness, bool compute_shannon, bool compute_simpson, bool compute_hill, double q);
RcppExport SEXP _biodivMapR_compute_alpha_diversity_metrics(SEXP abundancesSEXP, SEXP compute_richnessSEXP, SEXP compute_shannonSEXP, SEXP compute_simpsonSEXP, SEXP compute_hillSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_richness(compute_richnessSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_shannon(compute_shannonSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_simpson(compute_simpsonSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_hill(compute_hillSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_alpha_diversity_metrics(abundances, compute_richness, compute_shannon, compute_simpson, compute_hill, q));
    return rcpp_result_gen;
END_RCPP
}
// compute_jaccard_dissimilarity
NumericMatrix compute_jaccard_dissimilarity(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_jaccard_dissimilarity(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_jaccard_dissimilarity(A, B));
    return rcpp_result_gen;
END_RCPP
}
// compute_jaccard_turnover
NumericMatrix compute_jaccard_turnover(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_jaccard_turnover(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_jaccard_turnover(A, B));
    return rcpp_result_gen;
END_RCPP
}
// compute_sorensen_dissimilarity
NumericMatrix compute_sorensen_dissimilarity(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_sorensen_dissimilarity(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sorensen_dissimilarity(A, B));
    return rcpp_result_gen;
END_RCPP
}
// compute_simpson_dissimilarity
NumericMatrix compute_simpson_dissimilarity(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_simpson_dissimilarity(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_simpson_dissimilarity(A, B));
    return rcpp_result_gen;
END_RCPP
}
// compute_bray_curtis_dissimilarity
NumericMatrix compute_bray_curtis_dissimilarity(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_bray_curtis_dissimilarity(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_bray_curtis_dissimilarity(A, B));
    return rcpp_result_gen;
END_RCPP
}
// compute_bray_curtis_turnover
NumericMatrix compute_bray_curtis_turnover(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _biodivMapR_compute_bray_curtis_turnover(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_bray_curtis_turnover(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biodivMapR_compute_alpha_diversity_metrics", (DL_FUNC) &_biodivMapR_compute_alpha_diversity_metrics, 6},
    {"_biodivMapR_compute_jaccard_dissimilarity", (DL_FUNC) &_biodivMapR_compute_jaccard_dissimilarity, 2},
    {"_biodivMapR_compute_jaccard_turnover", (DL_FUNC) &_biodivMapR_compute_jaccard_turnover, 2},
    {"_biodivMapR_compute_sorensen_dissimilarity", (DL_FUNC) &_biodivMapR_compute_sorensen_dissimilarity, 2},
    {"_biodivMapR_compute_simpson_dissimilarity", (DL_FUNC) &_biodivMapR_compute_simpson_dissimilarity, 2},
    {"_biodivMapR_compute_bray_curtis_dissimilarity", (DL_FUNC) &_biodivMapR_compute_bray_curtis_dissimilarity, 2},
    {"_biodivMapR_compute_bray_curtis_turnover", (DL_FUNC) &_biodivMapR_compute_bray_curtis_turnover, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_biodivMapR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
