# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_jaccard_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_jaccard_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_jaccard_turnover <- function(A, B) {
    .Call('_biodivMapR_compute_jaccard_turnover', PACKAGE = 'biodivMapR', A, B)
}

compute_sorensen_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_sorensen_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_simpson_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_simpson_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_bray_curtis_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_bray_curtis_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_bray_curtis_turnover <- function(A, B) {
    .Call('_biodivMapR_compute_bray_curtis_turnover', PACKAGE = 'biodivMapR', A, B)
}

