# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_alpha_diversity_metrics <- function(abundances, compute_richness = TRUE, compute_shannon = TRUE, compute_simpson = TRUE, compute_hill = TRUE, q = 1.0) {
    .Call('_biodivMapR_compute_alpha_diversity_metrics', PACKAGE = 'biodivMapR', abundances, compute_richness, compute_shannon, compute_simpson, compute_hill, q)
}

compute_jaccard_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_jaccard_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_jaccard_turnover <- function(A, B) {
    .Call('_biodivMapR_compute_jaccard_turnover', PACKAGE = 'biodivMapR', A, B)
}

compute_sorensen_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_sorensen_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_simpson_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_simpson_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_bray_curtis_dissimilarity <- function(A, B) {
    .Call('_biodivMapR_compute_bray_curtis_dissimilarity', PACKAGE = 'biodivMapR', A, B)
}

compute_bray_curtis_turnover <- function(A, B) {
    .Call('_biodivMapR_compute_bray_curtis_turnover', PACKAGE = 'biodivMapR', A, B)
}

